name: Android MobileApp Deploy

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Select version number'
        required: true
        type: choice
        options:
          - build
          - patch
          - minor
          - major
        default: 'build'

jobs:
  qa-build:
    uses: ./.github/workflows/base_mobile_app_build.yml
    with:
      version_type: ${{ github.event.inputs.version_type }}
      environment: qa
    secrets: 
      AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      REPO_READ_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
      BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}

  prod-build:
    uses: ./.github/workflows/base_mobile_app_build.yml
    with:
      version_type: ${{ github.event.inputs.version_type }}
      environment: magnum
    secrets: 
      AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      REPO_READ_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
      BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}