name: Android Auto App Deploy
run-name: Android Auto App Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: magnum

    steps:
      - name: Check out wonderwhy folder
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          token: ${{ secrets.REPO_READ_TOKEN }}
          path: wonderWhy
          fetch-depth: 1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Inject Fastlane
        run: |
          cd wonderWhy
          mkdir -p flutterFlow/wonder_move_mobile/android/fastlane
          cp -r automation/androidFastlane/* flutterFlow/wonder_move_mobile/android/fastlane/
          cp -r automation/Gemfile flutterFlow/wonder_move_mobile/android/

      - name: Decode Keystore
        run: |
          cd wonderWhy
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode \
            > flutterFlow/wonder_move_mobile/android/app/keystore.jks

      - name: Create key.properties
        run: |
          cd wonderWhy
          cat <<EOF > flutterFlow/wonder_move_mobile/android/key.properties
          storeFile=keystore.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEYSTORE_PASSWORD }}
          EOF

      - name: Install Fastlane
        run: |
          cd wonderWhy/flutterFlow/wonder_move_mobile/android
          gem install bundler -v "~> 2.7"
          bundle install

      - name: Build & Upload to Google Play
        env:
          GCP_JSON_KEY: ${{ secrets.GCP_JSON_KEY }}
        run: |
          cd wonderWhy/flutterFlow/wonder_move_mobile/android
          bundle exec fastlane --version
          bundle exec fastlane upload_to_custom_track
